config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/welcome' => 'welcome#index'
  resources :categories do
    resources :products
  end

  resources :products do
    resources :reviews, :only => ['create', 'destroy']
  end
  root :to => 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :except => [:index,:show] do
    redirect_to new_user_session_path unless current_user && current_user.admin
  end
  def index
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Product saved!"
      redirect_to  categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category updated!"
      redirect_to  category_path(@category)
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.products.each do |prod|
      prod.destroy
    end
    @category.destroy
    redirect_to categories_path
  end

private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :except => [:show] do
      redirect_to new_user_session_path unless current_user && current_user.admin
    end

    def show
      @category = Category.find(params[:category_id])
      @product = Product.find(params[:id])
      @review = Review.new
    end

    def new
      @category = Category.find(params[:category_id])
      @product = Product.new
    end
    def create
      @category = Category.find(params[:category_id])
      @product = @category.products.new(product_params)
      if @product.save
        flash[:notice] = "Product saved!"
        redirect_to  category_path(@category)
      else
        render :new
      end
    end

    def edit
      @category = Category.find(params[:category_id])
      @product = Product.find(params[:id])
    end
    def update
      @category = Category.find(params[:category_id])
      @product = Product.find(params[:id])
      if @product.update(product_params)
        flash[:notice] = "Product updated!"
        redirect_to  category_product_path(@category, @product)
      else
        render :edit
      end
    end

    def destroy
      @category = Category.find(params[:category_id])
      @product = Product.find(params[:id])
      @product.reviews.each do |review|
        review.destroy
      end

      @product.destroy
      redirect_to category_path(@category)
    end

  private
    def product_params
      params.require(:product).permit(:name, :description, :price)
    end


end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, :only => [:create]
  before_action :only => [:delete] do
    redirect_to new_user_session_path unless current_user && current_user.admin
  end
  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    current_user.reviews.push(@review)
    @review.save
    redirect_to category_product_path(@product.category, @product)
  end

  def destroy
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to category_product_path(@product.category, @product)
  end

private
  def review_params
    params.require(:review).permit(:body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_admin?
    current_user && current_user.admin
  end
end

app/views/categories/_form.html.erb
<%= render "layouts/errors", :object => @category %>

<%= form_for @category do |c| %>
  <div class='form-group'>
    <%= c.label :name %>
    <%= c.text_field :name %>
  </div>
  <%= c.submit %>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1>All Categories</h1>

<ul>
  <% Category.all.each do |c| %>
    <li><%= link_to c.name, category_path(c) %></li>
  <% end %>
</ul>


<% if is_admin? %>
  <%= link_to 'Add Category', new_category_path, class:'btn btn-primary' %>
<% end %>

app/views/categories/new.html.erb
<h1>Add Category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<h3>Products</h3>
<% @category.products.all.each do |prod| %>
  <li><%= link_to prod.name, category_product_path(@category,prod) %></li>
<% end %>
<br><br>
<% if is_admin? %>
  <%= link_to "Add Product", new_category_product_path(@category), class:'btn btn-success'%>
<% end %>
<br>
<hr>
<% if is_admin? %>
  <%= link_to "Edit Category", edit_category_path(@category), class:'btn btn-success'%>
  <%= link_to "Delete Category", category_path(@category), :data => {:confirm => "Warning: This will delete all products in this category.", :method => "delete"}, class:'btn btn-danger'%>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MilesSmiles</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Miles of Smiles</a>
      </div>
      <div class="nav navbar-nav">
          <li><%= link_to 'Product Categories', categories_path %></li>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><a>Welcome <%=current_user.username%></a></li>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, :data => {:method=>'delete'} %></li>
        <% else %>
          <li><%= link_to 'Sign Up',  new_user_registration_path %></a></li>
          <li><%= link_to 'Sign In', new_user_session_path %></a></li>
        <% end %>
      </ul>
    </div>
  </nav>


  <div class="container">
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </div>

</html>

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for [@category,@product] do |c| %>
  <div class='form-group'>
    <%= c.label :name %>
    <%= c.text_field :name %>
  </div>
  <div class='form-group'>
    <%= c.label :description %>
    <%= c.text_field :description %>
  </div>
  <div class='form-group'>
    <%= c.label :price %>
    <%= c.text_field :price %>
  </div>
  <%= c.submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Category</h1>
<%= render 'form' %>

app/views/products/new.html.erb
<h1>Add Product</h1>
<%= render 'form' %>

app/views/products/show.html.erb
<h1><%=@product.name%></h1>
<img src="/300x300.jpg" alt="">
<h3>$<%='%.2f' % @product.price%></h3>
<h5><%=@product.description%></h5>
<% if is_admin? %>
<hr>
<%= link_to "Edit Product", edit_category_product_path(@category, @product), class:'btn btn-success'%>
<%= link_to "Delete Product", category_product_path(@category, @product), :data => {:confirm => "Warning: This will delete this product permanently.", :method => "delete"}, class:'btn btn-danger'%>
<% end %>
<hr>
<h3>Reviews</h3>

<% @product.reviews.each do |r| %>
<div class='review-box'>
  <h4><%= r.user.username %></h4>
  <p><%= r.body %></p>
  <% if is_admin? %>
    <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe, product_review_path(@product, r), :data => {:confirm => "Warning: This will delete this review permanently.", :method => "delete"}, class:'delete-review'%>
  <% end %>
</div>
<% end %>

<% if current_user %>
  <%= form_for [@product, @review] do |form| %>
    <h5>Review</h5>
    <%= form.text_field :body %>
    <%= form.submit %>
  <% end %>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<h1 id='title'>Welcome to Miles of Smiles</h1>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="item active">
      <img src="bootstrap-carousel.png" alt="Los Angeles">
    </div>

    <div class="item">
      <img src="bootstrap-carousel.png" alt="Chicago">
    </div>

    <div class="item">
      <img src="bootstrap-carousel.png" alt="New York">
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<hr>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa ratione, excepturi cum atque pariatur labore iste, necessitatibus veritatis dolorem esse, repellat cupiditate animi culpa earum est architecto soluta repudiandae optio. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto vitae, eius odio accusamus, mollitia facere quibusdam dolore ducimus? Illo quod eaque nemo eos ratione quaerat aperiam distinctio veniam maxime, est!</p>